### ISSUE TITLE
Signature Switch ate my mail

### ISSUE THREAD

**Issue by MayeulC** [4ch1m/mozext#53] opened 2021-12-16 19:06 UTC
I wrote a long e-mail, in two languages.

Both language were separated by (not sure about the number of dashes):

```
--------- English Version ----------
```

Below that, I had a bloc with a custom signature for the occasion.

I was about to send it, then on second thought, I added a new recipient. Due to automatic signature switching, half of my message was discarded, plus the custom signature (not a big deal for the signature). No obvious way to undo the operation.

* Thunderbird 91.4.0 (64 bits) -- Arch Linux. Composer in text mode.
* Signature switch 2.8.0

I lost an hour. I will disable the extension for now. Thankfully I still have half of it.

**Comment by 4ch1m** [comment] 2021-12-17 07:02
I can't reproduce this given this vague/little information.
A concrete example or a pull-request fixing this issue is always welcome.
May also be a duplicate of #52.

**Closed by 4ch1m** 2021-12-17 07:02 UTC
