### ISSUE TITLE
Email address is not saved in mail draft

### ISSUE THREAD

**Issue by halle-saale** [4ch1m/mozext#43] opened 2021-04-04 05:21 UTC
(Windows NT 10.0; Win64; x64; TB 88)

Steps to reproduce: I entered the email address, then a subject. Then I saved the mail as draft.
If I then want to edit it, the email address line is empty.

**Comment by 4ch1m** [comment] 2021-04-04 07:46
Works for me. (Linux; x86; [https://ftp.mozilla.org/pub/thunderbird/nightly/2021/04/2021-04-03-10-55-20-comm-central/thunderbird-89.0a1.en-US.linux-x86_64.tar.bz2](TB89))

**Comment by halle-saale** [comment] 2021-04-05 05:41
Since this is the only add-on I have installed and since it is working if I start TB with add-ons disabled: It has to be the reason!

**Comment by 4ch1m** [comment] 2021-04-05 09:24
I was able to reproduce this using my Windows machine. (Win10; x64; [TB89](https://releases.mozilla.org/pub/thunderbird/nightly/2021/04/2021-04-04-10-58-12-comm-central/thunderbird-89.0a1.en-US.win64.zip); Signature Switch 2.6.1)

Seems that this is yet another side-effect of the newly introduced "pillification" (see [Bugzilla](https://bugzilla.mozilla.org/show_bug.cgi?id=1696765#c24)).

Needs to be reported to the core TB-devs.
Done here: [Bugzilla](https://bugzilla.mozilla.org/show_bug.cgi?id=1702957).

Closing this issue.

**Closed by 4ch1m** 2021-04-05 09:24 UTC
