### ISSUE TITLE
Document auto switch email addresses have to be escaped

### ISSUE THREAD

**Issue by hokascha** [4ch1m/mozext#36] opened 2021-01-11 15:14 UTC
When adding a signature that has an auto switch filter for domain endings, for example: "*@*.com" the dot has to be escaped like in "*@*\.com". Not escaping the dot will let every email address containg "com" trigger the switch - not only those containing ".com".

This should be documented or automatically escaped.

**Comment by 4ch1m** [comment] 2021-01-11 16:02
Right.
That was a bug. => f004bb35a2bfa5aaa5bb08dfd92609ab426080c9
Will be fixed in next release.

**Closed by 4ch1m** 2021-01-11 16:02 UTC

**Comment by hokascha** [comment] 2021-01-11 19:10
While fixing this, could you also make sure, the filter will not get double escaped? I suppose people are circumventing the bug like me and escape their dots. These should not be escaped again. As the backslash is not a valid part of an email address this should be safe.

**Comment by 4ch1m** [comment] 2021-01-11 19:29
No, sorry.
This was a bug, and it has been fixed now.
I'd like to keep the code simple and not add additional code just to handle externally applied workarounds.
Should be easy/simple to correct this - as intended - via the UI.
