### ISSUE TITLE
Update lost all my settings

### ISSUE THREAD

**Issue by sphh** [4ch1m/mozext#40] opened 2021-03-19 15:39 UTC
I had SignatureSwitch configured for my use case and it was working well in TB 68. I used a "Pre-Load Executable".

Somewhere on the path to TB 78, this functionality got lost. Unfortunately I did not notice it immediately, because I have set the signature in the account settings to a very similar one.

The "Config editor …" shows the following `Preference Names`:
`extensions.signatureswitch.`

- `autoswitchpriorities`: `ANM`
- `composerpath`: `/usr/bin/xed`
- `contextmenu`: `false`
- `defaultsignature`: `0`
- `encoding`: `UTF-8`
- `initdelay`: `1000`
- `offbydefault`: `false`
- `preloadexecutable`: `true`
- `preloadexecutablepath`: `/home/<user>/bin/signature_switch`
- `preloadexecutablewait`: `true`
- `shortcut_cycle_key`: `C`
- `shortcut_cycle_modifier_accel`: `false`
- `shortcut_cycle_modifier_alt`: `false`
- `shortcut_cycle_modifier_control`: `true`
- `shortcut_cycle_modifier_meta`: `false`
- `shortcut_cycle_modifier_shift`: `true`
- `shortcut_onoff_key`: `Y`
- `shortcut_onoff_modifier_accel`: `false`
- `shortcut_onoff_modifier_alt`: `false`
- `shortcut_onoff_modifier_control`: `true`
- `shortcut_onoff_modifier_meta`: `false`
- `shortcut_onoff_modifier_shift`: `true`
- `signatures`: `Standard signature (gets overwritten by the pre-load executable)*%ProfD%/signature.txt* -----*-*-*-`

but all settings in SignatureSwitch configuration screen are empty.

How can I get the old settings into the new SignatureSwitch?

**Comment by 4ch1m** [comment] 2021-03-19 17:05
This is not a bug/issue.
Please read the [FAQ](http://mozext.achimonline.de/signatureswitch-me.php#faq) (# 7).
Closing.

**Closed by 4ch1m** 2021-03-19 17:05 UTC

**Comment by sphh** [comment] 2021-03-19 18:42
Sorry, I looked through the FAQs, but missed #7. Would be great, to have this info in more prominent place …

BTW, can I delete these old preferences?

**Comment by sphh** [comment] 2021-03-19 19:29
I also wanted to say, that it is much easier to have different automatic signatures for different identities. No fiddling with external scripts anmore. Great! Thanks.
