### ISSUE TITLE
2.4.0 apparently broken with Tbird 78.3.1 (fedora 31)

### ISSUE THREAD

**Issue by adunstan** [4ch1m/mozext#31] opened 2020-12-07 23:09 UTC
When I select a signature in the compose window it no longer inserts the signature in the message.

**Comment by 4ch1m** [comment] 2020-12-08 05:26
Works for me with TB 78.5.1 (Linux Mint 20).
Can't reproduce with this little information.
Closing.

**Closed by 4ch1m** 2020-12-08 05:26 UTC
